service:
  targetPort: 3000

# TODO: add all the stuff here
env:
  PORT: 3000
  MONGODB_DATABASE_NAME: docs_chat_prod

# TODO: add this via kubectl when database is created
# envSecrets:
#   MONGODB_CONNECTION_URI: chat-server-atlas-uri-prod

ingress:
  enabled: true
  hosts:
    - chat-server.docs.prod.corp.mongodb.com

# TODO: update this to do the elastic-beanstalky stuff
resources:
  limits:
    memory: 1300Mi
  requests:
    memory: 1100Mi
